# Import Library

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("C:/Users/Chintan/NewOne/Classification/Newfolder/train.csv")

In [3]:
df.shape

(891, 12)

In [4]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [5]:
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [6]:
df.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [7]:
df.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

Age have missing values.

**Data Preprocessing**

**Sex**

In [8]:
df['Sex'] = df['Sex'].replace(['male','female'],[0,1])
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name  Sex   Age  SibSp  Parch  \
0                            Braund, Mr. Owen Harris    0  22.0      1      0   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...    1  38.0      1      0   
2                             Heikkinen, Miss. Laina    1  26.0      0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)    1  35.0      1      0   
4                           Allen, Mr. William Henry    0  35.0      0      0   

             Ticket     Fare Cabin Embarked  
0         A/5 21171   7.2500   NaN        S  
1          PC 17599  71.2833   C85        C  
2  STON/O2. 3101282   7.9250   NaN        S  
3            113803  53.1000  C123        S  
4            373450   8.0500   NaN        S

**Embarked**

In [9]:
df['Embarked'].isna().sum()

2

In [10]:
df['Embarked'].fillna(df['Embarked'].value_counts().argmax(),inplace = True)

C:\Users\Chintan\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: 
The current behaviour of 'Series.argmax' is deprecated, use 'idxmax'
instead.
The behavior of 'argmax' will be corrected to return the positional
maximum in the future. For now, use 'series.values.argmax' or
'np.argmax(np.array(values))' to get the position of the maximum
row.
  """Entry point for launching an IPython kernel.


In [11]:
df['Embarked'] = df['Embarked'].replace(['C','Q','S'],[0,1,2])

In [12]:
df['Embarked'].unique()


array([2, 0, 1], dtype=int64)

**Age**

In [13]:
df['Age'] = df['Age'].fillna(df['Age'].median())

In [14]:
df['Age'].isna().sum()

0

**Cabin**

In [15]:
df['Cabin'].isna().value_counts()

True     687
False    204
Name: Cabin, dtype: int64

**Sibsp**

In [16]:
df['SibSp'].unique()

array([1, 0, 3, 4, 2, 5, 8], dtype=int64)

In [17]:
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name  Sex   Age  SibSp  Parch  \
0                            Braund, Mr. Owen Harris    0  22.0      1      0   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...    1  38.0      1      0   
2                             Heikkinen, Miss. Laina    1  26.0      0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)    1  35.0      1      0   
4                           Allen, Mr. William Henry    0  35.0      0      0   

             Ticket     Fare Cabin  Embarked  
0         A/5 21171   7.2500   NaN         2  
1          PC 17599  71.2833   C85         0  
2  STON/O2. 3101282   7.9250   NaN         2  
3            113803  53.1000  C123         2  
4            373450   8.0500   NaN         2

In [18]:
df.drop(columns=['Cabin','Name','PassengerId','Ticket'],inplace=True)

here we drop cabin, name, passengerid, ticket. because it's not usefull for prediction.

In [19]:
df.head()

Survived  Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
0         0       3    0  22.0      1      0   7.2500         2
1         1       1    1  38.0      1      0  71.2833         0
2         1       3    1  26.0      0      0   7.9250         2
3         1       1    1  35.0      1      0  53.1000         2
4         0       3    0  35.0      0      0   8.0500         2

In [20]:
df_train = df.copy()

In [21]:
df_train.shape

(891, 8)

**Now remove Outliers from train data**

remove outliers we use z-score mathod

In [22]:
cco = df_train.columns

In [23]:
df_train.isna().sum()

Survived    0
Pclass      0
Sex         0
Age         0
SibSp       0
Parch       0
Fare        0
Embarked    0
dtype: int64

In [24]:
for i in range(len(cco)):
    df_train[cco[i]] = df_train[cco[i]]/max(df_train[cco[i]])

from scipy import stats
import numpy as np
z = np.abs(stats.zscore(df_train))

df_train = df_train[(z < 3).all(axis=1)]
df_train.shape


(820, 8)

In [25]:
df_train.Survived.value_counts()

0.0    500
1.0    320
Name: Survived, dtype: int64

In [26]:
df_train.head()

Survived    Pclass  Sex     Age  SibSp  Parch      Fare  Embarked
0       0.0  1.000000  0.0  0.2750  0.125    0.0  0.014151       1.0
1       1.0  0.333333  1.0  0.4750  0.125    0.0  0.139136       0.0
2       1.0  1.000000  1.0  0.3250  0.000    0.0  0.015469       1.0
3       1.0  0.333333  1.0  0.4375  0.125    0.0  0.103644       1.0
4       0.0  1.000000  0.0  0.4375  0.000    0.0  0.015713       1.0

**Split Data**

In [27]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df_train.drop(columns=['Survived']),df_train['Survived'], test_size=0.33, random_state=42)

**Logistic Regression**

In [28]:
from sklearn.linear_model import LogisticRegression
clf = LogisticRegression(C = 1,max_iter=100,penalty='l1')
clf.fit(X_train,y_train)
clf.score(X_train,y_train)

C:\Users\Chintan\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


0.7723132969034608

In [29]:
y_pred = clf.predict(X_test)

In [30]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)

array([[152,  21],
       [ 24,  74]], dtype=int64)

**Rendom Forest**

In [31]:
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier()
clf.fit(X_train,y_train)
clf.score(X_train,y_train)

C:\Users\Chintan\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


0.9617486338797814

In [32]:
y_pred = clf.predict(X_test)

In [33]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)

array([[157,  16],
       [ 28,  70]], dtype=int64)

**MLP**

In [34]:
from sklearn.neural_network import MLPClassifier

# clf = MLPClassifier(solver='lbfgs', alpha=1e-5,
#                     hidden_layer_sizes=(5, 2), random_state=1)
clfm = MLPClassifier(solver='adam', activation='relu',alpha=1e-5,hidden_layer_sizes=(100,150,150,100), random_state=1,max_iter=100,verbose=5,learning_rate_init=0.001)

clfm.fit(X_train, y_train)

Iteration 1, loss = 0.68092717
Iteration 2, loss = 0.64504381
Iteration 3, loss = 0.61170705
Iteration 4, loss = 0.57670191
Iteration 5, loss = 0.53974961
Iteration 6, loss = 0.51256633
Iteration 7, loss = 0.49940990
Iteration 8, loss = 0.49494174
Iteration 9, loss = 0.49071362
Iteration 10, loss = 0.48030461
Iteration 11, loss = 0.47546877
Iteration 12, loss = 0.47256610
Iteration 13, loss = 0.46714752
Iteration 14, loss = 0.46640279
Iteration 15, loss = 0.46231088
Iteration 16, loss = 0.46014934
Iteration 17, loss = 0.45851513
Iteration 18, loss = 0.45710512
Iteration 19, loss = 0.45487852
Iteration 20, loss = 0.45473479
Iteration 21, loss = 0.45031693
Iteration 22, loss = 0.45110042
Iteration 23, loss = 0.45007573
Iteration 24, loss = 0.44912063
Iteration 25, loss = 0.44381608
Iteration 26, loss = 0.44750197
Iteration 27, loss = 0.44435460
Iteration 28, loss = 0.44445507
Iteration 29, loss = 0.44174284
Iteration 30, loss = 0.44211735
Iteration 31, loss = 0.44315289
Iteration 32, los

C:\Users\Chintan\Anaconda3\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:566: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


MLPClassifier(activation='relu', alpha=1e-05, batch_size='auto', beta_1=0.9,
              beta_2=0.999, early_stopping=False, epsilon=1e-08,
              hidden_layer_sizes=(100, 150, 150, 100), learning_rate='constant',
              learning_rate_init=0.001, max_iter=100, momentum=0.9,
              n_iter_no_change=10, nesterovs_momentum=True, power_t=0.5,
              random_state=1, shuffle=True, solver='adam', tol=0.0001,
              validation_fraction=0.1, verbose=5, warm_start=False)

In [35]:
clfm.score(X_train,y_train)

0.8178506375227687

In [36]:
y_pred = clfm.predict(X_test)

In [37]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)

array([[167,   6],
       [ 32,  66]], dtype=int64)